### ISSUE TITLE
halaman admin

### ISSUE THREAD

**Issue by rijwan212** [dhimasanb/silatboy#1]
halaman admin untuk : 
1. nge-post content "silatbetawi","event seminar & workshop".
2. nge-post galeri foto
3. nge-post galeri video
4. ngontrol formulir pendaftaran silat & formulir event seminar & workshop
5. ngontrol user yg login/daftar
6. ngontrol formulir silat yg diinput oleh user ke admin
7. ngontrol form kritik & saran dari user

**Comment by dhimasanb** [comment]
Update : 029cca44018529c23d0fed371ac0197105280b71
