### ISSUE TITLE
halaman daftar

### ISSUE THREAD

**Issue by rijwan212** [dhimasanb/silatboy#2]
halaman "daftar" diganti dengan "daftarkan silat". isinya : 
1. formulir pengajuan silat baru. isi formulirnya meliputi : 
* nama pencak silat : 
* alamat pencak silat : 
* Keterangan pencak silat : 
* logo pencak silat : 
* video pencak silat (link youtube) :
* contact person guru pencak silat :

**Comment by dhimasanb** [comment]
Update : 0c9fd0910a6018acf20b676cfe162cb361334002
